# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bonitasoft Documentation Prototype
email: pierre.belabbes@bonitasoft.com
description: >- # this means to ignore newlines until "baseurl:"
  This prototype has for purpose to rethink the documentation system
  of Bonitasoft using Jekyll. All documentation fiel are written in 
  markdown. There is three different github repository to retrieve them
  and each repo has different branches. Each representing a version of
  a product.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: 
github_username:  pbelabbes

# Build settings
markdown: kramdown

# theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Site permalink settings
permalink: /:title/
# End

# Collections settings
# collections:
#   bonita:
#     output: true
#     permalink: /:collection/:path

collections:
  bonita:
    output: true
    permalink: /:collection/:path
    github: "https://github.com/bonitasoft/bonita-doc/edit/7.7/md/"
    versions:
      - "7.7"
      - "7.6"
      - "7.5"
  bcd:
    output: true
    permalink: /:collection/:path
    github: "https://github.com/bonitasoft/bonita-continuous-delivery-doc/edit/2.0/md/"
    versions:
      - "2.0"
      - "1.0"
  ici:
    output: true
    permalink: /:collection/:path
    github: "https://github.com/bonitasoft/bonita-continuous-delivery-doc/edit/2.0/md/"
    versions:
      - "1.0"




# End

